config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root to: 'articles#index', as: :authenticated_root
    resources :articles
    get 'reports' => 'reports#index'
    post 'articles/:id/update_stock' => 'articles#update_stock', as: :update_article_stock
  end

  root to: redirect('auth/sign_in')
  devise_for :users, path: 'auth'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article saved!"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = "Article saved!"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def destroy
    if Article.destroy(params[:id])
      flash[:notice] = "Article deleted!"
    else
      flash[:alert] = "Article could not be deleted!"
    end
    redirect_to articles_path
  end

  def article_params
    params.require(:article).permit(:name, :price, :stock, :package_size, :barcode)
  end

  def update_stock
    flash['notice'] = "Stock updated."
    if params[:stock_type] == "units"
      update_stock_by_units
    else
      update_stock_by_packages
    end
  end

  def update_stock_by_units
    @article = Article.find(params[:id])
    @article.stock += params[:stock].to_i
    @article.save
    redirect_to articles_path
  end

  def update_stock_by_packages
    @article = Article.find(params[:id])
    @article.stock += params[:stock].to_i * @article.package_size
    @article.save
    redirect_to articles_path
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    a = 3+3
    @b = a - 2
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    #@data =
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def articles_controller?
    controller.controller_name == 'articles'
  end

  def reports_controller?
    controller.controller_name == 'reports'
  end

  def settings_controller?
    controller.controller_name == 'settings'
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
  def row_stock_class(article)
    return "danger" if article.stock < article.package_size * 2
  end
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? then %>
    <div class="alert alert-danger">
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for @article, html: {class: "form-horizontal"} do |f| %>
    <div class="form-group">
      <%= f.label :name, "Name *", class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :name, placeholder: "Name", class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :barcode, "Barcode *", class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :barcode, placeholder: "Barcode", class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :stock, "Stock *", class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :stock, placeholder: "Stock", class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :price, "Price *", class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :price, placeholder: "Price", class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :package_size, "Package size *", class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :package_size, placeholder: "Package size", class: "form-control" %>
      </div>
    </div>


    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-6">
        <%= f.submit "Save", class: "btn btn-primary" %>
        <%= link_to "Cancel", :back, class: "btn btn-default" %>
      </div>
    </div>
<% end %>

app/views/articles/create.html.erb
<h1>Article#create</h1>
<p>Find me in app/views/article/create.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Article#destroy</h1>
<p>Find me in app/views/article/destroy.html.erb</p>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<div class="clearfix">
  <h1 class="pull-left">Stock</h1>

  <a href="<%= new_article_path %>" class="pull-right btn btn-default hidden-xs">
    <span class="glyphicon glyphicon-plus"></span> Add Item
  </a>
</div>


<table class="table margin-top-2">
  <thead>
  <th>Name</th>
  <th class="text-right">Stock</th>
  <th class="text-right">Price</th>
  <th class="text-right">Package Size</th>
  <th>Stock change <span class="glyphicon glyphicon-info-sign" data-toggle="tooltip" data-placement="top" title="Enter a number and press 'Units' to add the given amount to the stock. You can choose 'Packages' to add the given amount of packages (look for the column 'Package Size'). Entering a negative amount subtracts the given amount."></span></th>
  <th>Manage</th>
  </thead>

  <tbody>

  <% @articles.each do |article| %>
      <tr class="<%= row_stock_class(article) %>">
        <td><%= article.name %></td>
        <td class="text-right"><%= if article.stock.nil? then 0 else article.stock end %></td>
        <td class="text-right"><%= number_to_currency(article.price, unit: "€", format: "%n %u") %></td>
        <td class="text-right"><%= article.package_size %></td>
        <td>
          <%= form_for article, url: update_article_stock_path(article), html: {class: "form-horizontal"}, method: "post" do |f| %>
              <input name="stock" type="number" value="1" />
              <button name="stock_type" value="units" class="btn btn-default">Units</button>
              <button name="stock_type" value="packages" class="btn btn-default">Packages</button>
          <% end %>
        </td>
        <td>
          <%= link_to "Edit", edit_article_path(article), class: "btn btn-primary" %>
          <%= link_to "Delete", article_path(article), method: :delete,
                      data: {confirm: "Do you really want to delete the article? "}, class: "btn btn-danger" %>
        </td>
      </tr>
  <% end %>

  </tbody>
</table>

app/views/articles/new.html.erb
<h1>Create article</h1>

<%= render 'form' %>

app/views/articles/update.html.erb
<h1>Article#update</h1>
<p>Find me in app/views/article/update.html.erb</p>

app/views/layouts/_flash.html.erb
<% if ! notice.nil? then %>
    <div class="alert alert-info"><%= notice %></div>
<% end %>

<% if ! alert.nil? then %>
    <div class="alert alert-danger"><%= alert %></div>
<% end %>

app/views/layouts/_flash_growl.html.erb
<% if ! notice.nil? then %>
    <div class="alert alert-info growl"><%= notice %></div>
<% end %>

<% if ! alert.nil? then %>
    <div class="alert alert-danger growl"><%= alert %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CashRegister</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<div class="container">

  <div class="main-content-box">
    <%= image_tag "header.png", class: "img-responsive" %>



    <div role="tabpanel">

      <%= render "layouts/flash_growl" %>

      <!-- Nav tabs -->
      <ul id="navigation" class="nav nav-tabs" role="tablist">
        <li role="presentation" class="<%= 'active' if articles_controller? %>"><a href="<%= articles_path %>">Stock</a></li>
        <li role="presentation" class="<%= 'active' if reports_controller? %>"><a href="<%= reports_path %>">Report</a></li>
        <li role="presentation" class="<%= 'active' if settings_controller? %>"><a href="#settings" role="tab" data-toggle="tab">Settings</a></li>

        <li role="presentation" class="pull-right">
          <%= link_to "Sign out", destroy_user_session_path,:method => :delete %>
        </li>
      </ul>

      <!-- Tab panes -->
      <div class="tab-content">
        <%= yield %>
      </div>
    </div>
  </div>

</div>


</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CashRegister</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
    <%= image_tag "header.png", class: "img-responsive header-login" %>
</div>

<div class="container main-content-box login">

  <%= yield %>

</div>

</body>
</html>

app/views/reports/index.html.erb
<h1>Reports</h1>

<div id="chart">

</div>

<script type="text/javascript">
    new Morris.Line({
        // ID of the element in which to draw the chart.
        element: 'chart',
        // Chart data records -- each entry in this array corresponds to a point on
        // the chart.
        data: [
            { year: '2008', value: 20 },
            { year: '2009', value: 10 },
            { year: '2010', value: 5 },
            { year: '2011', value: 5 },
            { year: '2012', value: 20 }
        ],
        // The name of the data record attribute that contains x-values.
        xkey: 'year',
        // A list of names of data record attributes that contain y-values.
        ykeys: ['value'],
        // Labels for the ykeys -- will be displayed when you hover over the
        // chart.
        labels: ['Value']
    });
</script>